---

- name: instalar net-tools
  dnf:
    name: "net-tools"
    state: latest
  become: true

- name: habilitar nfs-server
  systemd:
    name: "nfs-server"
    state: "started"
    enabled: yes
    masked: no
  become: true

- name: crear directorio nfs
  file: 
    path: "{{ nfs_ruta }}"
    state: directory
    owner: root
    group: root
    mode: 0751
  become: true

- name: crear fichero /etc/exports
  template: 
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  become: true

- name: reload service nfsd
  command: "exportfs -rs"
  become: true

- name: configurar firewall service
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ lista }}"
  become: true
  
- name: reload service firewalld
  systemd: 
    name: "firewalld" 
    state: "reloaded"
  become: true