---

- name: configurar firewalld port
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ lista }}"
  become: true

- name: add worker cluster
  command: "{{ comando }}"
  become: true