---

- name: configurar firewalld port
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ lista }}"
  become: true

- name: configurar kudeadm
  command: kubeadm config images pull
  become: true

- name: configurar firewalld rich-rule
  firewalld:
    rich_rule: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ rich_rules }}"
  become: true

#- name: instalar plugin CNI
#  command: kubeadm init --pod-network-cidr {{ network_pod }}/16
#  register: output_kubeadm
#  become: true

- name: guardar token
  command: kubeadm token create --print-join-command
  register: output_token
  become: true
- debug: var=output_token.stdout_lines