---

- name: configurar firewalld port
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ lista }}"
  become: true

- name: configurar kudeadm
  command: kubeadm config images pull
  become: true

- name: configurar firewalld rich-rule
  firewalld:
    rich_rule: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ rich_rules }}"
  become: true

#- name: instalar plugin CNI
#  command: kubeadm init --pod-network-cidr {{ network_pod }}/16
#  register: output_kubeadm
#  become: true

- name: guardar token
  command: kubeadm token create
  register: output_token
  become: true
- debug: var=output_token.stdout_lines

#- name: guardar output_token /tmp/output_token.log
#  copy:
#    src: "{{ output_token.stdout }}"
#    dest:  /tmp/output_token.log
#    owner: root
#    group: root
#    mode: 0644
#  delegate_to: localhost
#  become: true