---

- name: Remove repository devel:kubic:libcontainers:stable.repo (and clean up left-over metadata)
  yum_repository:
    name: kubic-stable.repo
    file: kubic-stable.repo
  become: true

- name: Remove repository devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo (and clean up left-over metadata)
  yum_repository:
    name: kubic-cri-o:1.23:1.23.1.repo
    file: kubic-cri-o:1.23:1.23.1.repo
  become: true

- name: Remove repository devel:kubic:libcontainers:stable.repo (and clean up left-over metadata)
  yum_repository:
    name: devel:kubic:libcontainers:stable.repo
    file: devel:kubic:libcontainers:stable.repo
  become: true

- name: Remove repository devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo (and clean up left-over metadata)
  yum_repository:
    name: devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
    file: devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
  become: true