---

hosts_names: ["{{ hosts_ips[1] }}" 'kubemaster.acme.es', "{{ hosts_ips[2] }}" 'kubenode1 kubenode1.acme.es', "{{ hosts_ips[2]}}" 'nfs nfs.acme.es'] #master, workers, nfs

lista: ['kubelet', 'kubeadm', 'kubectl']

exclude: 'kubernetes'


