---

- name: install haproxy
  dnf:
    name: "{{ lista }}"
    state: latest
  become: yes

- name: copy haproxy configuration file
  template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
    setype: etc_t
  become: yes

- name: habilitar SELinux
  selinux:
    state: enforcing
    policy: targeted
  become: true

- name: reboot para aplicar cambios (como selinux)
  reboot:
  become: true
  
- name: configure selinux booleans for haproxy
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes
  become: yes

- name: habilitar haproxy
  systemd:
    name: "haproxy"
    state: restarted
    enabled: yes
    masked: no
    daemon_reload: yes
  become: yes

- name: firewall configuration for nodeport
  firewalld:
    port: "{{ sqlport }}/{{ protocol }}"
    permanent: yes
    state: enabled
    immediate: yes
  become: true