---

- name: crear diretorio apps
  file: 
    path:  /apps
    state: directory
    owner: adminUsername
    group: adminUsername
  become: true

- name: crear mysql.yaml
  template:
    src: mysql.j2
    dest:  /apps/mysql.yaml
  
- name: deploy app mysql
  command: kubectl apply -f /apps/mysql.yaml