---

- name: Configuracion nfs
  hosts: nfs
  vars_files:
    - "group_vars/ips-privadas.yaml" # Tener disponibles IPs privadas para fichero exports del nfs
    - "group_vars/nfs-configuration.yaml"
  gather_facts: no
  roles:
    - nfs-configuration