---

- name: Configuracion master k8s
  hosts: master
  vars_files:
    - "group_vars/ips-privadas.yaml" # Tener disponibles IP network_pod para plugin CNI
    - "group_vars/k8s-master-configuration.yaml"
  gather_facts: no
  roles:
    - k8s-master-configuration