---

- name: configurar /etc/hosts
  hosts: master, workers
  vars_files:
    - "group_vars/vars_k8s.yaml"
  gather_facts: no
  tasks:
    - name: configurar /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
        create: yes
      with_items: "{{ lista }}"
      become: true

- name: activar firewalld
  hosts: master, workers
  vars:
    servicio: "firewalld"
  gather_facts: no
  roles:
    - servicio

#- name: AllowZoneDrifting
#  hosts: master, workers

- name: activar transparent masqueranding
  hosts: master, workers
  gather_facts: no
  tasks:
    - name: modprobe br_netfilter
      command: modprobe br_netfilter
      become: true
    - name: masquerade
      command: firewall-cmd --add-masquerade --permanent
      become: true
    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded
      become: true

- name: trafico cortafuegos
  hosts: master, workers
  gather_facts: no
  roles:
    - cortafuegos

- name: desactivar swap
  hosts: master, workers
  gather_facts: no
  tasks:
    - name: desactivar swap
      command: swapoff  -a
      become: true

#- name: eliminar linea fstab
#  hosts: master, workers

#- name: wget CRI-O
#  hosts: master, workers

#- name: kernel CRI-O
#  hosts: master, workers

#- name: install CRI-O
#  hosts: master, workers

#- name: enable CRI-O
#  hosts: master, workers

#- name: start CRI-O
#  hosts: master, workers

#- name: repo kubernetes
#  hosts: master, workers

#- name: instalamos kubernetes
#  hosts: master, workers

#- name: activar kubelet
#  hosts: master, workers
#  vars:
#    servicio: "kubelet"
#  gather_facts: no
#  roles:
#    - servicio