---

- name: configurar /etc/hosts
  hosts: master, workers
  vars_files:
    - "group_vars/vars_k8s.yaml"
  gather_facts: no
  tasks:
    - name: configurar /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
        create: yes
      with_items: "{{ lista }}"
      become: true

- name: activar firewalld
  hosts: master, workers
  vars:
    servicio: "firewalld"
  gather_facts: no
  roles:
    - servicio

#- name: AllowZoneDrifting
#  hosts: master, workers

- name: activar transparent masqueranding
  hosts: master, workers
  gather_facts: no
  tasks:
    - name: modprobe br_netfilter
      command: modprobe br_netfilter
      become: true
    - name: masquerade
      command: firewall-cmd --add-masquerade --permanent
      become: true
    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded
      become: true

- name: trafico cortafuegos
  hosts: master, workers
  gather_facts: no
  roles:
    - cortafuegos

- name: desactivar swap
  hosts: master, workers
  gather_facts: no
  tasks:
    - name: desactivar swap
      command: swapoff  -a
      become: true
    - name: eliminar linea swap
      command: sed -i '/swap/d' /etc/fstab
      become: true


- name: Add repo CRI-O
  hosts: master, workers
  tasks:
    - name: wget devel:kubic:libcontainers:stable.repo 
      yum_repository:
        name: devel:kubic:libcontainers:stable.repo
        description: devel:kubic:libcontainers:stable.repo
        file: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo
        baseurl: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo
        gpgcheck: no
    - name: wget  devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
      yum_repository:
        name: devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
        description: devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
        file:  /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
        baseurl: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
        gpgcheck: no

#- name: kernel CRI-O
#  hosts: master, workers

#- name: install CRI-O
#  hosts: master, workers

#- name: enable CRI-O
#  hosts: master, workers

#- name: start CRI-O
#  hosts: master, workers

#- name: repo kubernetes
#  hosts: master, workers

#- name: instalamos kubernetes
#  hosts: master, workers

#- name: activar kubelet
#  hosts: master, workers
#  vars:
#    servicio: "kubelet"
#  gather_facts: no
#  roles:
#    - servicio