---

- name: k8s firewall
  hosts: master
  vars_files:
    - "group_vars/firewall_k8s_worker2.yaml"
  gather_facts: no
  roles:
    - firewall4


- name: add cluster
  hosts: master
  gather_facts: no
  tasks:
    - name: add cluster
      command: kubeadm join 192.168.1.24:6443 --token yha7ux.9ez5yp2yrgtz1a73 --discovery-token-ca-cert-hash sha256:5761830722e421ee2724c24642829d5b4f8f47b7e041bd429a7ac0a9fc59888a
      become: true