---

- name: ingress controller
  hosts: master
  gather_facts: no
  tasks:
    - name: ingress controller
      command: kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/master/deploy/haproxy-ingress.yaml
      become: true

       