---

- name: configurar /etc/hosts
  hosts: master, workers
  vars_files:
    - "group_vars/vars_k8s.yaml"
  gather_facts: no
  tasks:
    - name: configurar /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
        create: yes
      with_items: "{{ lista }}"
      become: true

- name: activar firewalld
  hosts: master, workers
  vars:
    servicio: "firewalld"
  gather_facts: no
  roles:
    - servicio

#- name: transparent masqueranding
#  hosts: master, workers

#- name: trafico cortafuegos
#  hosts: master, workers

#- name: desactivar swap
#  hosts: master, workers

#- name: eliminar linea fstab
#  hosts: master, workers

#- name: wget CRI-O
#  hosts: master, workers

#- name: kernel CRI-O
#  hosts: master, workers

#- name: install CRI-O
#  hosts: master, workers

#- name: enable CRI-O
#  hosts: master, workers

#- name: start CRI-O
#  hosts: master, workers

#- name: repo kubernetes
#  hosts: master, workers

#- name: instalamos kubernetes
#  hosts: master, workers

#- name: activar kubelet
#  hosts: master, workers
#  vars:
#    servicio: "kubelet"
#  gather_facts: no
#  roles:
#    - servicio