---

- name: configurar /etc/hosts
  hosts: master, workers
  vars_files:
    - "group_vars/vars_k8s.yaml"
  gather_facts: no
  tasks:
    - name: configurar /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
        create: yes
      with_items: "{{ lista }}"
      become: true

- name: activar firewalld
  hosts: master, workers
  vars:
    servicio: "firewalld"
  gather_facts: no
  roles:
    - servicio

#- name: AllowZoneDrifting
#  hosts: master, workers

- name: activar transparent masqueranding
  hosts: master, workers
  gather_facts: no
  tasks:
    - name: modprobe br_netfilter
      command: modprobe br_netfilter
      become: true
    - name: masquerade
      command: firewall-cmd --add-masquerade --permanent
      become: true
    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded
      become: true

- name: trafico cortafuegos
  hosts: master, workers
  gather_facts: no
  roles:
    - cortafuegos

- name: desactivar swap
  hosts: master, workers
  gather_facts: no
  tasks:
    - name: desactivar swap
      command: swapoff  -a
      become: true
    - name: eliminar linea swap
      command: sed -i '/swap/d' /etc/fstab
      become: true

- name: Add repo CRI-O
  hosts: master, workers
  gather_facts: no
  roles:
    - crio

- name: instalar CRI-O
  hosts: master, workers
  vars_files:
    - "group_vars/paquete_crio.yaml"
  gather_facts: no
  roles:
    - instalar

- name: habilitar CRI-O
  hosts: master, workers
  vars:
    servicio: "crio"
  gather_facts: no
  roles:
    - servicio

#- name: Add repo kubernetes
#  hosts: master, workers
#  gather_facts: no
#  roles:
#    - kubernetes

#- name: instalar kubernetes
#  hosts: master, workers
#  vars_files:
#    - "group_vars/paquete_kubernetes.yaml"
#  gather_facts: no
#  roles:
#    - instalar

#- name: habilitar kubelet
#  hosts: master, workers
#  vars:
#    servicio: "kubelet"
#  gather_facts: no
#  roles:
#    - servicio