---

- name: sdn
  hosts: master
  gather_facts: no
  tasks:
    - name: operator tigera
      command: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
      become: true
    - name: wget calico
      command: wget https://docs.projectcalico.org/manifests/custom-resources.yaml
      become: true
    - name: apply calico
      command: kubectl apply -f custom-resources.yaml
      become: true
    - name: get nodes
      command: kubectl get nodes
      register: output_nodes
      become: true
    - name: get pods
      command: kubectl get pods -A
      register: output_pods
      become: true

#- name: reboot