---

- name: k8s firewall
  hosts: master
  vars_files:
    - "group_vars/firewall_k8s_worker2.yaml"
  gather_facts: no
  roles:
    - firewall

#puertos
#[root@kubenodeX ~]# firewall-cmd --zone=public --permanent --add-port={10250,30000-32767}/tcp
#[root@kubenodeX ~]# firewall-cmd --reload

- name: add cluster
  hosts: master
  gather_facts: no
  tasks:
    - name: add cluster
      command: kubeadm join 192.168.1.110:6443 --token gmk4le.8gsfpknu99k78qut --discovery-token-ca-cert-hash sha256:d2cd35c9ab95f4061aa9d9b993f7e8742b2307516a3632b27ea10b64baf8cd71
      become: true