---

- name: k8s firewall
  hosts: master
  vars_files:
    - "group_vars/firewall_k8s.yaml"
  gather_facts: no
  roles:
    - firewall

- name: configurar kudeadm
  hosts: master
  gather_facts: no
  tasks:
    - name: configurar kudeadm
      command: kubeadm config images pull
      become: true

- name: acceso worker firewall
  hosts: master
  vars_files:
    - "group_vars/firewall_k8s_worker.yaml"
  gather_facts: no
  roles:
    - firewall3

- name: instalar plugin CNI
  hosts: master
  gather_facts: no
  tasks:
    - name: instalar plugin CNI
      command: kubeadm init --pod-network-cidr 192.169.0.0/16
      register: output_kubeadm
      become: true

- name: guardar output_kubeadm /unirdevopsscp2/ansible
  copy:
    src: output_kubeadm
    dest:  /unirdevopsscp2/ansible/output_kubeadm
    owner: root
    group: root
    mode: 0644
  become: true

#- name: acceso root cluster
#  hosts: master
#  gather_facts: no
#  tasks:
#    - name: kubeconfig
#      command: export KUBECONFIG=/etc/kubernetes/admin.conf
#      become: true
#    - name: dir .kube
#      command: mkdir -p /root/.kube
#      become: true
#    - name: file .kube/config
#      command: cp -i /etc/kubernetes/admin.conf /root/.kube/config
#      become: true
#    - name: own .kube/config
#      command: chown $(id -u):$(id -g) /root/.kube/config
#      become: true
#    - name: kubectl
#      command: kubectl get nodes
#      become: true