---

#- name: crear usuario admin
#  user:
#    name: "{{ user }}"
#    password: "{{ user | password_hash('sha512') }}"
#  become: true

- name: configurar kube de usuario admin. Crear directorio.
  file: 
    path:  /home/{{ user }}/.kube/
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  become: true

- name: configurar kube de usuario admin. Copiar fichero (become:true escala en write no en lectura y no funciona con copy)
  command: cp -i /etc/kubernetes/admin.conf /home/{{ user }}/.kube/config
  become: true

- name: configurar kube de usuario admin. Permisos fichero.
  file: 
    path:  /home/{{ user }}/.kube/config
    owner: "{{ user }}"
    group: "{{ user }}"
  become: true

- name: configurar sudoers.d de usuario admin
  template:
    src: user.j2
    dest:  /etc/sudoers.d/{{ user }}
    owner: root
    group: root
    mode: 0644
  become: true